Increase number of stored copies
OSLL/github_backup_utils pull request #8
Opened 2024-11-20 12:14 UTC by KonstantinKondratenko

2024-11-20 12:20 UTC, KonstantinKondratenko commented
Использовать вот так:
1. нужно разместить на уровне, где лежат каталоги
2. `./keep_n_backups_for_templates.sh N folder1 [folder2 ... folderN]`
Тут N - количество копий
требуется как минимум 1 папка, иначе скрипт ломается


скрипт копирует в ../backups папки и называет их `<имя>_месяц_день_час_минуты` 
Потом если папок (которые начинаются на `<имя>`) больше, чем N, то удаляет количество - N

2024-11-20 13:14 UTC, zmm commented on keep_n_backups_for_templates.sh
> +  local timestamp=$(date +"%m_%d_%H_%M")
Добавьте год четырьмя цифрами в самое начало

2024-11-20 13:21 UTC, KonstantinKondratenko commented on keep_n_backups_for_templates.sh
> +  local timestamp=$(date +"%m_%d_%H_%M")
Добавил (тут d1a5e47513a0c5ff47d1fc88e90f50c5556ae587 )степерь выглядит так:
`<name>_2024_11_20_16_18`

2024-11-20 13:21 UTC, zmm requested changes

2024-11-20 13:21 UTC, zmm commented on keep_n_backups_for_templates.sh
> +  local new_folder_name="${folder}_${timestamp}"
Я бы перед копированием добавил отладочный вывод - что начинаем такой-то каталог копировать.

2024-11-20 13:21 UTC, zmm commented on keep_n_backups_for_templates.sh
> +    for ((i=0; i<num_to_delete; i++)); do
Нужен отладочный вывод перед попыткой удаления.

2024-11-20 13:21 UTC, zmm commented on keep_n_backups_for_templates.sh
> +#!/bin/bash
Добавьте второй строкой set -e

2024-11-20 13:21 UTC, zmm commented on keep_n_backups_for_templates.sh
> +  echo "Usage: $0 N folder1 [folder2 ... folderN]"
Поясните, как интерпретируются аргументы folderN

2024-11-20 13:21 UTC, zmm commented on keep_n_backups_for_templates.sh
> +for folder in "${FOLDERS[@]}"; do
По задумке folder1 [folder2 ... folderN] это подстроки от начала имен папок. 
Например, у нас могут быть папки вида:
pr-2023-1, pr-2024-5, cs-2025-6

Мы передаем в качестве аргументов:
pr-2023- и cs-2025-

соответственно, должны быть обработаны только каталоги, которые начинаются с одной из этих подстрок.

2024-11-20 13:26 UTC, KonstantinKondratenko commented on keep_n_backups_for_templates.sh
> +for folder in "${FOLDERS[@]}"; do
хм, понял, пока работает так, что нужно прописать полные название копируемых папок (pr-2023-3381 pr-2023-3382 и тд)

2024-11-20 13:32 UTC, KonstantinKondratenko commented on keep_n_backups_for_templates.sh
> +#!/bin/bash
Добавил в 275dde98dc6fed210950a1d3c107584676af4b1a

2024-11-20 13:32 UTC, KonstantinKondratenko commented on keep_n_backups_for_templates.sh
> +  local new_folder_name="${folder}_${timestamp}"
Добавил в 275dde98dc6fed210950a1d3c107584676af4b1a

2024-11-20 13:32 UTC, KonstantinKondratenko commented on keep_n_backups_for_templates.sh
> +    for ((i=0; i<num_to_delete; i++)); do
Добавил в 275dde98dc6fed210950a1d3c107584676af4b1a

2024-11-20 13:35 UTC, KonstantinKondratenko commented on keep_n_backups_for_templates.sh
> +  echo "Usage: $0 N folder1 [folder2 ... folderN]"
пока реализовано так:
передаем N - число хранимых копий
а потом как минимум 1 папку, но можно и больше папок, которые копируем, то есть для 1 курса пми по проге будет выгляжеть так:
`./keep_n_backups_for_templates.sh 5 pr-2024-4381 pr-2024-4382 pr-2024-4383 pr-2024-4384 pr-2024-4385 pr-2024-4388`

2024-11-20 13:35 UTC, KonstantinKondratenko commented on keep_n_backups_for_templates.sh
> +  echo "Usage: $0 N folder1 [folder2 ... folderN]"
да, у меня не очень удачное описание, тут N количество и folderN никак не свзяаны в них N

2024-11-20 13:56 UTC, KonstantinKondratenko commented on keep_n_backups_for_templates.sh
> +for folder in "${FOLDERS[@]}"; do
добавил prefix
теперь запускать нужно так:
 `./new.sh 5 pr-2024`
 
 Вот как будет выглядеть вывод: 
 ```
Start copy pr-2024-4388 into ../backups/pr-2024-4388_2024_11_20_16_53
Folder pr-2024-4388 copied into ../backups/pr-2024-4388_2024_11_20_16_53
Start copy pr-2024-4382 into ../backups/pr-2024-4382_2024_11_20_16_53
Folder pr-2024-4382 copied into ../backups/pr-2024-4382_2024_11_20_16_53
Start copy pr-2024-4381 into ../backups/pr-2024-4381_2024_11_20_16_53
Folder pr-2024-4381 copied into ../backups/pr-2024-4381_2024_11_20_16_53
Start copy pr-2024-4383 into ../backups/pr-2024-4383_2024_11_20_16_53
Folder pr-2024-4383 copied into ../backups/pr-2024-4383_2024_11_20_16_53
Start copy pr-2024-4384 into ../backups/pr-2024-4384_2024_11_20_16_53
Folder pr-2024-4384 copied into ../backups/pr-2024-4384_2024_11_20_16_53
Start copy pr-2024-4385 into ../backups/pr-2024-4385_2024_11_20_16_53
Folder pr-2024-4385 copied into ../backups/pr-2024-4385_2024_11_20_16_53
Started deleting ../backups/pr-2024-4388_2024_11_20_16_44
Deleted old copy ../backups/pr-2024-4388_2024_11_20_16_44
Started deleting ../backups/pr-2024-4382_2024_11_20_16_44
Deleted old copy ../backups/pr-2024-4382_2024_11_20_16_44
Started deleting ../backups/pr-2024-4381_2024_11_20_16_44
Deleted old copy ../backups/pr-2024-4381_2024_11_20_16_44
Started deleting ../backups/pr-2024-4383_2024_11_20_16_44
Deleted old copy ../backups/pr-2024-4383_2024_11_20_16_44
Started deleting ../backups/pr-2024-4384_2024_11_20_16_44
Deleted old copy ../backups/pr-2024-4384_2024_11_20_16_44
Started deleting ../backups/pr-2024-4385_2024_11_20_16_44
Deleted old copy ../backups/pr-2024-4385_2024_11_20_16_44
```

2024-11-25 13:48 UTC, HadronCollider approved these changes
В целом, ок - добавил в джобу бакапов

до 02.12 смотрим - потом мержим

2025-01-21 11:57 UTC, merged